Range slider bug fix 981
ramneet-persistent/observability pull request #7
Opened 2022-09-01 15:39 UTC by ramneet-persistent

### Description
range slider min/max bug

### Issues Resolved
[#981](https://github.com/opensearch-project/observability/issues/981)

2022-09-05 11:46 UTC, abasatwar requested changes

2022-09-05 11:46 UTC, abasatwar commented on dashboards-observability/common/types/explorer.ts
> +  chartStyles: any;
avoid any

2022-09-05 11:46 UTC, abasatwar commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/config_bar_chart_styles.tsx
> +          if (schema.eleType === 'input') {
change this if to switch

2022-10-17 09:09 UTC, ramneet-persistent commented
Merged via [Pull #1122](https://github.com/opensearch-project/observability/pull/1122)

2022-10-17 09:09 UTC, closed without merging