Config panel collapse icon issue
ramneet-persistent/observability pull request #8
Opened 2022-09-06 04:50 UTC by ramneet-persistent

collapse icon issue resolved

2022-09-16 12:52 UTC, spattnaik requested changes

2022-09-16 12:52 UTC, spattnaik commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/index.tsx
> +              aria-label="aria-label-1"
Use proper label. `aria-label-1` is not a proper one. This can be the panel name.

2022-09-16 12:52 UTC, spattnaik commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/index.tsx
> +    <EuiResizableContainer onToggleCollapsed={onCollapse} aria-label="aria-label-container">
Do not use `aria-label` term in `aria-label`. This is what screen-readers will read, which does not make any sense. Read about it before using.

2022-09-16 12:52 UTC, spattnaik commented on dashboards-observability/public/components/event_analytics/explorer/visualizations/index.tsx
> +              aria-label="aria-label-2"
Same as above comment

2022-10-11 11:29 UTC, ramneet-persistent commented
Fields section and data config resize configuration is modified and collapse icon on fields section is not visible now.
so closing this PR

2022-10-11 11:29 UTC, closed without merging